import Head from 'next/head'
import { Montserrat } from '@next/font/google'
import Feed from '@/components/feed/feed';

const montserrat = Montserrat({ subsets: ['latin']});

export default function Home() {
  return (
    <>
      <Head>
        <title>Finde</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={montserrat.className}>
        <Feed />
      </div>
    </>
  )
}
